apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: kube-public
webhooks:
- name: validating-webhook.example.com
  admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGRENDQWZ5Z0F3SUJBZ0lVS0NLK2pVQUdjSCs4OXlrTXRYd2dCUkpBR1FZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF4TVhRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnUTBFd0hoY05NVGt4TWpJMgpNRFkxTVRBd1doY05NalF4TWpJME1EWTFNVEF3V2pBaU1TQXdIZ1lEVlFRREV4ZEJaRzFwYzNOcGIyNGdRMjl1CmRISnZiR3hsY2lCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5QQlIzRlcKc0xmQWoxQ0xua3kyak9IMWdlMms5NjYzbTFST3d4WVFoK1NFS2JGWlE5QTd3YjlVTGxQM01CUFpxd0VTMmdaLwphYksxbHJNRkhCZzhBbmtkem9YeDlkWmNoYkxFaWtWdERXckNmUWJVMG50MDVpYnlpSGpOZ0ZZbVNLOUwrU1dGCjJwZDJOZWF3ZUl4VjU1SVh2NDBZQkdJK2pmZndnTDIzaDBzU3RVQVRITW9sL1hJU3JhcmlpVjhMdlBTK3dnWWUKaHBmVmJDZGpXMzdMUE15UU9RaWVKSlpkUDZpRVdDRlJ0OGRLM2M1QzJrejdNcFZLZVhqUHpnS0E5QXZlM2t1bgpGQVEvdFdkRGdoU0l1TGMzR0FWWEdJYUp3R3JGTzZteXhCbi9hRWtUOGExcEtmWkhNcGorb1QxUGRXTlI4Z2thCkZjSG9oL1pQd2FJV3FvOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGRkhQKzhBVWJHWEFFcFQ0VFdnUlFoMURrZU9NTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQUpoMXJMcHo0Q1N2TDZqNWl1ekpHQzMrZEFOQWV1WFZWZlBvQXREbnFNVThDNmZKTVhVaDJvCmo2S1BXdVJjbE0rMTZPRWhKWHI5ZEdNeUNvY0ltdGlBZFV1dlRlendMcStnVzZIdFdBZjhCM0VBUURGVUMwckUKamY0NFRoOFgvRmsrUlBFNUZIV05CVWtPdnk0c0xuNDB2emdlbnBwWTZZZUk1WHZaU0c0VlFXYmtkaHJzVmFTSQoxMjJvZDZscVI5bTVwZ1JWbjl4Y3VySCtWMmZQLzdrMlpqTmZ5RUxhaWZQMVNqTTNWTkw0T1dKc0tvQnA3ODVYCmFaeGEwMXUrNkJwS0NkZzVvSE5uM2gxamVaYTJZMzh6SWhPZitLelRPcFAwdFBDaWNHQXZHQ3R1NTE1YjR6eXoKTjBBb0ZSSkIxeDRESjFBMURDNmFiZ093RjZTRm5kVjkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: admission-controller
      namespace: kube-public
      path: "/"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
  sideEffects: None
  timeoutSeconds: 5
